apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-infrastructure
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/DarcusGrey/employee-config'
    targetRevision: main
    path: cluster-infra/
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - SkipDryRunOnMissingResource=true