# namespace: employee #Setting in the argoCD yaml file means I no longer need to define this

server:
  appName: server
  path: /api/v1/employees
  image:
    name: darcusgrey/employee-app
    tag: latest
  containerPort: 8080
  deplName: server-deployment
  svcName: server-service
  svcPort: 8080
  hpa:
    name: server-hpa
    minReplicas: 3
    maxReplicas: 5

database:
  appName: db
  replicas: 1
  containerName: postgres
  containerPort: 5432
  svcName: db-service
  svcPort: 5432
  statefulSetName: db-statefulset
  volumeMounts:
    name: pgdata
    mountPath: /var/lib/postgresql

gatewayClassName: gateway-class-cilium
gatewayName: employee-gateway

networkPolicy:
  enabled: true

secretName: my-secret
sealingSecret: false 
