{{- if .Values.networkPolicy.enabled }}
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
    name: {{ .Release.Namespace }}-isolation
    namespace: {{ .Release.Namespace }}
spec:
    # This policy applies to all pods in the employee namespace
    endpointSelector: {} 
    ingress:
    # Rule 1: Allow intra-namespace communication (frontend to backend, backend to db)
    - fromEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": {{ .Release.Namespace }}
        
    # Rule 2: Native Cilium rule allowing Gateway/Envoy traffic from the host
    - fromEntities:
        - ingress
        - host
        - remote-node
{{- end }}