{{- if .Values.sealingSecret}} 
apiVersion: v1
kind: Secret
metadata:
    name: {{.Values.clusterName}}-{{ .Values.secretName }}
type: Opaque
stringData:
    DB_USER: {{ .Values.secrets.username }}
    DB_PASS: {{ .Values.secrets.password }}
    DB_NAME: {{ .Values.database.appName }}
    DB_URL: jdbc:postgresql://{{ .Values.database.svcName }}:5432/{{ .Values.database.appName }}
{{- end}}