apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.server.deplName}}
  # namespace: {{.Values.namespace}}
spec:
  selector:
    matchLabels:
      app: {{.Values.server.appName}}
  template:
    metadata:
      labels:
        app: {{.Values.server.appName}}
    spec:
      containers:
      - name: {{.Values.server.appName}}
        image: "{{.Values.server.image.name}}:{{.Values.server.image.tag}}"
        # imagePullPolicy: Never #Use for local images
        ports:
        - containerPort: {{.Values.server.containerPort}}
        envFrom:
        - secretRef:
            name: {{.Values.secretName}}
        
        resources:
          requests:
            cpu: "250m"
          limits:
            cpu: "500m"

        livenessProbe:
            httpGet:
              path: {{.Values.server.path}}
              port: {{.Values.server.containerPort}}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 4

        readinessProbe:
          httpGet:
            path: {{.Values.server.path}}
            port: {{.Values.server.containerPort}}
          initialDelaySeconds: 2
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.server.svcName}}
  # namespace: {{.Values.namespace}}
  annotations:
    # This tells Cilium to load-balance this service across the mesh
    service.cilium.io/global: "true"
spec:
  type: ClusterIP
  selector:
    app: {{.Values.server.appName}}
  ports:
  - protocol: TCP
    port: {{.Values.server.svcPort}}
    targetPort: {{.Values.server.containerPort}}

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{.Values.server.hpa.name}}
  # namespace: {{.Values.namespace}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{.Values.server.deplName}}
  minReplicas: {{.Values.server.hpa.minReplicas}}
  maxReplicas: {{.Values.server.hpa.maxReplicas}}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50


