apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2" # Deploys before other apps
spec:
  project: default
  source:
    repoURL: https://helm.cilium.io/
    targetRevision: 1.19.5
    chart: cilium
    helm:
      values: |
        cluster:
          name: "my-cluster"
          id: 1
        ipam:
          mode: "kubernetes"
        operator:
          replicas: 1
        kubeProxyReplacement: true
        # Add these two lines for local Minikube execution, Replace ServiceHost with your actual `minikube ip`
        k8sServiceHost: "192.168.49.2" 
        k8sServicePort: 8443
        envoy:
          enabled: true
        gatewayAPI:
          enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true